language: ruby
rvm:
- 2.2

before_script:
 - gem install jekyll -v 3.1.6
 - gem install jekyll-paginate
 - gem install jekyll-feed
 # - npm install -g firebase-tools

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
 - rm -rf public
 - jekyll build -d public
 # - firebase deploy --token "${FIREBASE_TOKEN}"

deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the deploy branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

